matrix:
  include:
    - os: linux
      sudo: false
      compiler: gcc
      env: CC=gcc-4.9 CXX=g++-4.9
    - os: linux
      sudo: false
      compiler: clang
      env: CC=clang CXX=clang++
    - os: osx
      compiler: clang
      osx_image: xcode6.4
      env: CC=clang CXX=clang++

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - zlib1g-dev
    - lcov
    - ruby
    - rubygems

before_script:
  source .travis/before_script.sh

script:
  source .travis/script.sh
