language: cpp

matrix:
  allow_failures:
    - os: osx
  include:
    - os: linux
      sudo: false
      compiler: gcc
    - os: osx
      compiler: clang

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.9
    - zlib1g-dev
    - lcov
    - ruby
    - rubygems

before_script:
  source .travis/before_script.sh

script:
  source .travis/script.sh
